language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  - provider: surge
    skip_cleanup: true
    project: ./build/
    domain: srinjoy.me
  - provider: surge
    skip_cleanup: true
    project: ./build/
    domain: dev.$TRAVIS_BRANCH.srinjoy.me
    on:
      all_branches: true
stages:
  - name: cleanup
    if: type IN (pull_request)
    script: surge teardown dev.$TRAVIS_PULL_REQUEST_BRANCH.srinjoy.me
