language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  - provider: surge
    skip_cleanup: true
    project: ./build/
    domain: www.srinjoy.me
  - provider: surge
    skip_cleanup: true
    project: ./build/
    domain: srinjoy.me
  - provider: surge
    skip_cleanup: true
    project: ./build/
    domain: srinjoy.me/$branch
    on:
      all_branches: true
