notifications:
  email: false

language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

stages:
  - lint
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: lint
      script: npm run lint
    - &deploy
      stage: deploy
      script: npm run build
      deploy:
        - provider: surge
          skip_cleanup: true
          project: ./build/
          domain: www.srinjoy.me
        - provider: surge
          skip_cleanup: true
          project: ./build/
          domain: www.dev.srinjoy.me
          on:
            branch: master
